### PR TITLE
automatic download of missing audio files

### PR DESCRIPTION
**Pull request by mikolajjuda**
# Database
Removed ```file``` column from ```songs``` table
This will have to be removed manually in existing databases
New songs are added to database only after download and normalization
# Files
Music files are named after YouTube id
To migrate from previous system with randomly generated file names removal of audio files from ```Music``` directory will be necessary
# Missing audio files download
Added automatic download of missing audio files, it's triggered by adding new song, attempt to play (manually or automatically) a song with missing audio file or sending any POST request to ```/api/player/download``` endpoint as admin
Desired file is played after download
This should make transfer between machines easier as it's no longer necessary to transfer audio files as well, only the database
# Other
Separated Play and Pause buttons in admin panel to allow for not playing not yet playing music after download
Added refresh button to suggestions
Some code formatting
## Notes
I tried implementing automatic refresh after sending suggestion but I couldn't find a way to pass ```refreshSuggestions``` function from ```Suggestions``` component to ```Suggest``` component
It would make more sense functionally if ```Suggest``` component was child of ```Suggestions``` component

### CODE REVIEW

**Comment by etiaro** [comment]
Notes:
1. Due to code formatter, changed files is completely unreadable. We should use some linter and apply it to all files in future.
2. Also we should add some tests and workflows to be sure PRs doesn't broke any features.

PR:
1. I'd rather not get rid of file column. It's here for future support of direct .mp3 upload. Instead, we can move to assign ytid to filename by default. Optionally something like <ytid>.yt.mp3 . For migration delete all mp3's and run SQL which will change file=ytid
2. Good job about missing files download. Anyway, I can't test it for now and file changes are unreadable on mobile, so I'll comment the code later.

**Comment by etiaro** [comment]
Okay, some things to discuss:
1. I would do missing file validation in other way: load all songs from db and then find in js missing ones, because I'm not sure if sending so long SQL so often as it is done now is a good idea.
2. Fix missing songs on startup.
3. I'm not sure if file checkup on every download won't affect performance too much. Consider adding separate button to fix missing files

**Comment by mikolajjuda** [comment]
> Notes:
> 
> 1. Due to code formatter, changed files is completely unreadable. We should use some linter and apply it to all files in future.
> 2. Also we should add some tests and workflows to be sure PRs doesn't broke any features.

That would be extremely useful. Sorry about the formatter.

> PR:
> 
> 1. I'd rather not get rid of file column. It's here for future support of direct .mp3 upload. Instead, we can move to assign ytid to filename by default. Optionally something like .yt.mp3 . For migration delete all mp3's and run SQL which will change file=ytid

Sure, I'll add it back.

> Okay, some things to discuss:
> 
> 1. I would do missing file validation in other way: load all songs from db and then find in js missing ones, because I'm not sure if sending so long SQL so often as it is done now is a good idea.

Good point, I'll redo it.

> 2. Fix missing songs on startup.

Good idea, I'll add that.

> 3. I'm not sure if file checkup on every download won't affect performance too much. Consider adding separate button to fix missing files

Sure, I'll change that.

**Comment by mikolajjuda** [comment]
- I've added file column back. No migration is required, old files will be used if they exist, downloaded or re-downloaded songs will have their file column updated to new naming convention.

- Missing files check is now done by downloading all songs from database and checking if files exist.

- Missing files fix is now triggered at the end of player init.

- Downloads no longer trigger missing files download. I added ```/api/player/sync``` endpoint that triggers missing files download on PUT request. I also added sync icon in MusicToolbar that sends this request on click.

**Comment by etiaro** [comment]
Okay, for me it sounds okay. Sorry but I won't do any code-review this time. @PangolinGiLA feel free to merge it

**Pull request merged**
